include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    discarded_futures: ignore
    avoid_dynamic_calls: ignore
  exclude:
    - lib/l10n/gen/*
linter:
  rules:
    public_member_api_docs: false
